---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    postgresql_user: root
    postgresql_password: root_password

  tasks:
  - name: Import PostgreSQL repository key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Add PostgreSQL APT Repository
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
      state: present
      update_cache: yes

  - name: Install necessary packages
    apt:
      name:
        - postgresql
        - python3-psycopg2
      state: present

  - name: Ensure PostgreSQL is running
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: Allow all incoming connections to PostgreSQL
    lineinfile:
      path: /etc/postgresql/13/main/pg_hba.conf
      regexp: '^host all all 127.0.0.1/32 md5'
      line: 'host all all 0.0.0.0/0 md5'
    notify: Restart PostgreSQL

  - name: Listen on all addresses
    lineinfile:
      path: /etc/postgresql/13/main/postgresql.conf
      regexp: '^#?listen_addresses'
      line: "listen_addresses = '*'"
    notify: Restart PostgreSQL

  - name: Create the PostgreSQL user using psql command
    command:
      cmd: "sudo -u postgres psql -c \"CREATE USER {{ postgresql_user }} WITH PASSWORD '{{ postgresql_password }}' CREATEDB;\""

  handlers:
  - name: Restart PostgreSQL
    service:
      name: postgresql
      state: restarted

