---
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars:
    postgresql_user: postgres
    postgresql_password: root_password
    postgresql_version: 13
    postgresql_port: 5432

  tasks:
  - name: Import PostgreSQL repository key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Add PostgreSQL APT Repository
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
      state: present
      update_cache: yes

  - name: Install necessary packages
    apt:
      name:
        - postgresql-{{ postgresql_version }}
        - python3-psycopg2
      state: present

  - name: Ensure PostgreSQL is running
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: Allow all incoming connections to PostgreSQL
    lineinfile:
      path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
      regexp: '^host all all 127.0.0.1/32 md5'
      line: 'host all all 0.0.0.0/0 md5'
    notify: Restart PostgreSQL

  - name: Listen on all addresses
    lineinfile:
      path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
      regexp: '^#?listen_addresses'
      line: "listen_addresses = '*'"
    notify: Restart PostgreSQL

  - name: Set password for the PostgreSQL user
    become: yes
    become_user: postgres
    command:
      cmd: "psql -c \"ALTER USER {{ postgresql_user }} WITH PASSWORD '{{ postgresql_password }}';\""
    when: postgresql_user == "postgres"

  handlers:
  - name: Restart PostgreSQL
    service:
      name: postgresql
      state: restarted

